### ISSUE TITLE
.bash files

### ISSUE THREAD

**Issue by smartsammler** [detailyang/pre-commit-shell#3]
Is there a reason why `.bash` files are not supported, but only ` files: (\.sh|\.zsh|\.ksh)$` (in the `.pre-commit-hooks.yaml`)?

**Comment by detailyang** [comment]
Hello.
It's just personal hobbies. it's rare to use `.bash` as the suffix:)

BTW, PR welcome.

**Comment by rpdelaney** [comment]
Why zsh? I thought shellcheck doesn't support that. Or am I mistaken?
